[package]
name = "frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = "0.6.3"

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
