name: GitHub Pages Deployment

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Dioxus Deployment"
        uses: DioxusLabs/deploy-action@0.1.2
        with:
          outDirectory: "../target/dx/frontend/release/web/public"
          rootPath: "frontend"
