name: GitHub Pages Deployment

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Run clippy
        run: cargo clippy --verbose
      - name: Run tests
        run: cargo test --verbose
  build-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          target: wasm32-unknown-unknown
          toolchain: nightly
      - uses: Swatinem/rust-cache@v2
      - name: Install dioxus-cli
        run: cargo install dioxus-cli@0.7.0-alpha.3
      - name: Build Dioxus project
        run: cd frontend && dx build --release --verbose && cp ../target/dx/frontend/release/web/public/index.html ../target/dx/frontend/release/web/public/404.html && cd ..
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          clean: false
          folder: target/dx/frontend/release/web/public
